stages:
  - build

.nvm_env: &nvm_env
  tags:
    - redshift
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - . "$NVM_DIR/nvm.sh"
  
build:
  <<: *nvm_env
  stage: build
  when: manual
  script:
    - yarn
    - tar czf node_modules.tar.gz node_modules/
    - mkdir -p artifacts/
    - mv node_modules.tar.gz artifacts/
  artifacts:
    - artifacts/
